using Basalt.Confidentiality.Crypto;
using FluentAssertions;
using Xunit;

namespace Basalt.Confidentiality.Tests;

/// <summary>
/// The #1 flagship-risk test: a Groth16 verification key and proof produced by <b>gnark</b> (Go,
/// gnark-crypto's compressed BLS12-381 serialization) must be byte-compatible with Basalt's
/// <b>blst</b>-backed <see cref="Groth16Verifier"/>. Both follow the ZCash/IETF compressed-point
/// convention (big-endian, three MSB flag bits, G2 as A1‖A0), but that had never been cross-checked —
/// every existing Groth16 vector is blst-native, round-tripped inside Basalt. If the two encodings
/// diverged in any bit, <see cref="Groth16Verifier.Verify"/> would return false here.
/// </summary>
/// <remarks>
/// Vectors generated by <c>tools/basalt-prove</c> (<c>go run .</c>): gnark v0.15 Groth16 over BLS12-381,
/// trivial circuit proving knowledge of X with X*X == Y and Y = 9 public, serialized in the
/// <see cref="Groth16Codec"/> layout. The circuit is deliberately trivial so this isolates the
/// gnark↔blst point ENCODING, not any circuit logic.
/// </remarks>
public class GnarkCrossEncodingTests
{
    private const string VkHex =
        "a1573c423c0e452adf5d2d6b711d129f6315ce9a8ba036b2691c3fa5ce654da85d9606e56d699e6abe7aabb8257bc5c8" +
        "855f529bea728c25b894e0951a9b81fca2b891c7a79d011c2dacc146ef6ae4999ae328aea8d1feb9b830f59cb888b422" +
        "0b6be4ab7eefa9063609f7aa9ed63302946668fabf20fd3fb3c89f17b6a0174e8506c4459b3a74e0d93aeb3f9a10b57f" +
        "a04c9ea2553a50e182dee1c6672e0a1fe64673c1a50c9b4dc252875767d1b166360650ff515762efec2235d60ba2e2c1" +
        "09c03de29d198de7b919f78269fa8f259581a99bb94bc00c16b4377ba2fd9384576c43f7f89caf8cbd206346be6ab81b" +
        "8d3f530b3b1006eb8edcc413a982647a3cd4ebee21795a883a8a9769c2b0a7c4b9cf53a8d9b4135224dcb38f4592ec2c" +
        "0d83dc0443a2c9e0eb5be138ec089275b8d7f7b251aeac41863cea83091978a4bcfe9ac774dcb0594c2dfc6bd81fded4" +
        "02000000a6bae9f14d31ad5ba9a4a1250c19f4b818109b10a9d812014d33d85b11b932c81159a93f67954b58b6a78fc0" +
        "4c53a291869cf3e8c31c9d3660000662710224216f26edf9d3d37824abf5a9ec8a2605afa12d05188ad3a9a7612206c4" +
        "72618b8b";

    private const string ProofHex =
        "b51026213f9f442ca420a27d9044fa8236a5929da06275cf8a60ab586b3d09fc81334db2b6d4429a1fb368aa563246fa" +
        "92cb0919bfeb6eec25ef1f1c057af0cd6c6746b9d9ab66c3971f7bf253bd14a69518aa4f88e467cba3aefe311e446d38" +
        "16ec695f224f4f5ab733d28b23e59c6998431beab0d190c89b5c81c56a949fedb1b7a9237e3028d6a0a3965591971537" +
        "9776d0ab0008903e482ba21db5839403fd0e4951780f6198ad10bbb2c685b1e79b0d7f7d8e8f80b6498dec02fa9c0c8b";

    private const string PublicInputHex =
        "0000000000000000000000000000000000000000000000000000000000000009";

    private static byte[][] PublicInputs() => [Convert.FromHexString(PublicInputHex)];

    [Fact]
    public void GnarkProof_DecodesAndVerifies_UnderBlstVerifier()
    {
        var vk = Groth16Codec.DecodeVerificationKey(Convert.FromHexString(VkHex));
        var proof = Groth16Codec.DecodeProof(Convert.FromHexString(ProofHex));

        vk.IC.Should().HaveCount(2); // constant term + one public input

        Groth16Verifier.Verify(vk, proof, PublicInputs()).Should().BeTrue(
            "a gnark-crypto compressed VK+proof must decode and verify identically under blst " +
            "(the flagship gnark↔blst cross-encoding must match bit-for-bit)");
    }

    [Fact]
    public void GnarkProof_WrongPublicInput_FailsVerification()
    {
        var vk = Groth16Codec.DecodeVerificationKey(Convert.FromHexString(VkHex));
        var proof = Groth16Codec.DecodeProof(Convert.FromHexString(ProofHex));

        var wrong = new byte[32];
        wrong[31] = 8; // Y = 8, but the proof is for Y = 9

        Groth16Verifier.Verify(vk, proof, [wrong]).Should().BeFalse();
    }

    [Fact]
    public void GnarkProof_SwappedProofElements_FailsVerification()
    {
        var vk = Groth16Codec.DecodeVerificationKey(Convert.FromHexString(VkHex));
        var proof = Groth16Codec.DecodeProof(Convert.FromHexString(ProofHex));

        // A and C are both valid G1 points, so swapping keeps the encoding valid but the proof wrong.
        var swapped = new Groth16Proof { A = proof.C, B = proof.B, C = proof.A };

        Groth16Verifier.Verify(vk, swapped, PublicInputs()).Should().BeFalse();
    }
}
