name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement. Please describe your idea below.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've considered?
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Core
        - Crypto
        - Storage
        - Network
        - Consensus
        - Execution
        - Compliance (ZK / Attestations)
        - Confidentiality (Pedersen / Channels)
        - API (gRPC/GraphQL/REST)
        - SDK (Contracts / Analyzers / Testing)
        - SDK Wallet
        - Generators (Contracts / Codec / JSON)
        - Node
        - Explorer
        - CLI
        - DevNet
        - Bridge
        - Other
