namespace Basalt.Codec;

/// <summary>
/// Interface for types that can be serialized/deserialized using BasaltWriter/BasaltReader.
/// Implementations should be generated by Basalt.Generators.Codec source generator.
/// </summary>
public interface IBasaltSerializable<T> where T : IBasaltSerializable<T>
{
    /// <summary>
    /// Write this instance to the writer.
    /// </summary>
    void WriteTo(ref BasaltWriter writer);

    /// <summary>
    /// Read an instance from the reader.
    /// </summary>
    static abstract T ReadFrom(ref BasaltReader reader);

    /// <summary>
    /// Calculate the serialized size in bytes.
    /// </summary>
    int GetSerializedSize();
}

/// <summary>
/// Attribute to trigger source generation of IBasaltSerializable implementation.
/// </summary>
[AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
public sealed class BasaltSerializableAttribute : Attribute;

/// <summary>
/// Utility methods for serialization.
/// </summary>
public static class BasaltSerializer
{
    /// <summary>
    /// Serialize an instance to a byte array.
    /// </summary>
    public static byte[] Serialize<T>(T value) where T : IBasaltSerializable<T>
    {
        var size = value.GetSerializedSize();
        var buffer = new byte[size];
        var writer = new BasaltWriter(buffer);
        value.WriteTo(ref writer);
        return buffer;
    }

    /// <summary>
    /// Deserialize an instance from a byte array.
    /// </summary>
    public static T Deserialize<T>(ReadOnlySpan<byte> data) where T : IBasaltSerializable<T>
    {
        var reader = new BasaltReader(data);
        return T.ReadFrom(ref reader);
    }
}
