namespace Basalt.Sdk.Contracts;

/// <summary>
/// Computes FNV-1a method selectors used by the source-generated contract dispatch.
/// These selectors match the ones generated by Basalt.Generators.Contracts.
/// </summary>
public static class SelectorHelper
{
    /// <summary>
    /// Compute a 4-byte FNV-1a selector for a method name.
    /// </summary>
    public static uint ComputeSelector(string methodName)
    {
        uint hash = 2166136261;
        foreach (char c in methodName)
        {
            hash ^= (byte)c;
            hash *= 16777619;
        }
        return hash;
    }

    /// <summary>
    /// Compute a 4-byte FNV-1a selector as little-endian bytes.
    /// </summary>
    public static byte[] ComputeSelectorBytes(string methodName)
    {
        var sel = ComputeSelector(methodName);
        return
        [
            (byte)(sel & 0xFF),
            (byte)((sel >> 8) & 0xFF),
            (byte)((sel >> 16) & 0xFF),
            (byte)((sel >> 24) & 0xFF),
        ];
    }
}
