using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Basalt.Generators.Contracts;

/// <summary>
/// Writes the encoder for every type marked <c>[BasaltEvent]</c>.
///
/// It runs off the event declaration rather than off the contracts that emit it, so a type shared by
/// several contracts is generated once, and an event nobody emits yet is still ready when someone does.
/// </summary>
[Generator]
public sealed class EventCodecGenerator : IIncrementalGenerator
{
    private const string BasaltEventAttribute = "Basalt.Sdk.Contracts.BasaltEventAttribute";
    private const string IndexedAttribute = "Basalt.Sdk.Contracts.IndexedAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var events = context.SyntaxProvider.ForAttributeWithMetadataName(
            BasaltEventAttribute,
            predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
            transform: static (ctx, _) => GetEventInfo(ctx))
            .Where(static e => e is not null);

        context.RegisterSourceOutput(events, static (spc, info) => Generate(spc, info!));
    }

    private static EventCodecInfo? GetEventInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
            return null;

        // A nested event would need its containing types emitted as partial too. None exist, and
        // silently skipping one would put an event on chain with no fields, which is the failure this
        // generator was written to end. So it is reported instead.
        if (type.ContainingType is not null)
            return new EventCodecInfo(null, type.Name, false, [], Nested: true);

        var properties = new List<EventPropertyCodecInfo>();
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop
                || prop.DeclaredAccessibility != Accessibility.Public
                || prop.IsStatic
                || prop.GetMethod is null)
            {
                continue;
            }

            properties.Add(new EventPropertyCodecInfo(
                prop.Name,
                prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                HasIndexedAttribute(prop)));
        }

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();

        return new EventCodecInfo(ns, type.Name, type.IsRecord, properties, Nested: false);
    }

    private static bool HasIndexedAttribute(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() == IndexedAttribute)
                return true;
        }

        return false;
    }

    private static void Generate(SourceProductionContext spc, EventCodecInfo info)
    {
        if (info.Nested)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NestedEventRule, Location.None, info.TypeName));
            return;
        }

        var keyword = info.IsRecord ? "record" : "class";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.Append("namespace ").Append(info.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(keyword).Append(' ').Append(info.TypeName)
          .AppendLine(" : global::Basalt.Sdk.Contracts.IBasaltEvent");
        sb.AppendLine("{");

        AppendToLogData(sb, info);
        sb.AppendLine();
        AppendToLogTopics(sb, info);

        sb.AppendLine("}");

        spc.AddSource($"{info.TypeName}.Codec.g.cs", sb.ToString());
    }

    private static void AppendToLogData(StringBuilder sb, EventCodecInfo info)
    {
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public byte[] ToLogData()");
        sb.AppendLine("    {");

        if (info.Properties.Count == 0)
        {
            sb.AppendLine("        return [];");
            sb.AppendLine("    }");
            return;
        }

        sb.AppendLine("        int __size =");
        for (int i = 0; i < info.Properties.Count; i++)
        {
            sb.Append(i == 0 ? "              " : "            + ")
              .AppendLine(SizeExpression(info.Properties[i]));
        }

        sb.AppendLine("            ;");
        sb.AppendLine("        var __buffer = new byte[__size];");
        sb.AppendLine("        var __writer = new global::Basalt.Codec.BasaltWriter(__buffer);");

        foreach (var prop in info.Properties)
            sb.Append("        ").AppendLine(WriteStatement(prop, "__writer"));

        sb.AppendLine("        return __buffer[..__writer.Position];");
        sb.AppendLine("    }");
    }

    private static void AppendToLogTopics(StringBuilder sb, EventCodecInfo info)
    {
        var indexed = new List<EventPropertyCodecInfo>();
        foreach (var prop in info.Properties)
        {
            if (prop.Indexed)
                indexed.Add(prop);
        }

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::Basalt.Core.Hash256[] ToLogTopics()");
        sb.AppendLine("    {");

        if (indexed.Count == 0)
        {
            sb.AppendLine("        return [];");
            sb.AppendLine("    }");
            return;
        }

        sb.Append("        var __topics = new global::Basalt.Core.Hash256[")
          .Append(indexed.Count).AppendLine("];");

        for (int i = 0; i < indexed.Count; i++)
        {
            var prop = indexed[i];
            sb.AppendLine("        {");
            sb.Append("            var __b = new byte[").Append(SizeExpression(prop)).AppendLine("];");
            sb.AppendLine("            var __w = new global::Basalt.Codec.BasaltWriter(__b);");
            sb.Append("            ").AppendLine(WriteStatement(prop, "__w"));
            sb.Append("            __topics[").Append(i)
              .AppendLine("] = global::Basalt.Crypto.Blake3Hasher.Hash(__b[..__w.Position]);");
            sb.AppendLine("        }");
        }

        sb.AppendLine("        return __topics;");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Upper bound on a property's encoding. Variable-length values are measured rather than guessed,
    /// because the writer works into a fixed span and a short buffer would revert a working contract.
    /// </summary>
    private static string SizeExpression(EventPropertyCodecInfo prop) => prop.FullTypeName switch
    {
        "bool" or "byte" => "1",
        "ushort" => "2",
        "uint" or "int" => "4",
        "ulong" or "long" => "8",
        "global::Basalt.Core.Address" => "20",
        "global::Basalt.Core.Hash256" or "global::Basalt.Core.UInt256" => "32",
        "string" => $"10 + global::System.Text.Encoding.UTF8.GetByteCount(this.{prop.Name} ?? \"\")",
        "byte[]" => $"10 + (this.{prop.Name}?.Length ?? 0)",
        "ulong[]" => $"10 + (8 * (this.{prop.Name}?.Length ?? 0))",

        // Unsupported types are refused at build time by WriteStatement, which reports the diagnostic.
        _ => "0",
    };

    /// <summary>
    /// How a property is written. Null is encoded as empty rather than throwing, so a field left unset
    /// costs a log its contents and not the transaction that emitted it.
    /// </summary>
    private static string WriteStatement(EventPropertyCodecInfo prop, string writer) => prop.FullTypeName switch
    {
        "bool" => $"{writer}.WriteBool(this.{prop.Name});",
        "byte" => $"{writer}.WriteByte(this.{prop.Name});",
        "ushort" => $"{writer}.WriteUInt16(this.{prop.Name});",
        "uint" => $"{writer}.WriteUInt32(this.{prop.Name});",
        "int" => $"{writer}.WriteInt32(this.{prop.Name});",
        "ulong" => $"{writer}.WriteUInt64(this.{prop.Name});",
        "long" => $"{writer}.WriteInt64(this.{prop.Name});",
        "global::Basalt.Core.Address" => $"{writer}.WriteAddress(this.{prop.Name});",
        "global::Basalt.Core.Hash256" => $"{writer}.WriteHash256(this.{prop.Name});",
        "global::Basalt.Core.UInt256" => $"{writer}.WriteUInt256(this.{prop.Name});",
        "string" => $"{writer}.WriteString(this.{prop.Name} ?? \"\");",
        "byte[]" => $"{writer}.WriteBytes(this.{prop.Name} ?? []);",
        "ulong[]" => $"{{ var __a = this.{prop.Name} ?? []; {writer}.WriteVarInt((ulong)__a.Length); "
                     + $"foreach (var __v in __a) {writer}.WriteUInt64(__v); }}",
        _ => $"#error Basalt: event property '{prop.Name}' has unsupported type {prop.FullTypeName}",
    };

    private static readonly DiagnosticDescriptor NestedEventRule = new(
        id: "BSLT003",
        title: "Event type must be top level",
        messageFormat: "Event '{0}' is nested. Move it to namespace scope so its encoder can be generated, "
                       + "since an event without an encoder reaches the chain with no fields.",
        category: "Basalt.Contracts",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private sealed record EventCodecInfo(
        string? Namespace,
        string TypeName,
        bool IsRecord,
        List<EventPropertyCodecInfo> Properties,
        bool Nested);

    private sealed record EventPropertyCodecInfo(string Name, string FullTypeName, bool Indexed);
}
